import { Catering } from "./app/shared/models/Catering";

export const sample_catering: Catering[] = [
    {
    id: 'C01',
    name: 'Amigo\'s Catering',
    location: 'Naga Branch',
    tags: ['Amigos','Naga'],
    favorite: false,
    stars: 4.0,
    imageUrl: 'assets/C01 - Amigos_Catering.jpg',
    origins: ['Naga branch amigos'],
    cateringPacks: ['25 Packs', '50 Packs', '100 Packs'],
    },
    {
    id: 'C02',
    name: 'Ma. Lina\'s_Catering',
    location: 'Punta Branch',
    tags: ['Maria Lina','Punta'],
    favorite: false,
    stars: 3.0,
    imageUrl: 'assets/C02 - Ma. Lina_Catering.jpg',
    origins: ['Punta branch amigos'],
    cateringPacks: ['25 Packs', '50 Packs', '100 Packs'],
    },
    {
    id: 'C03',
    name: 'Athena\'s Catering',
    location: 'Gorordo Branch',
    tags: ['Athena','Gorordo'],
    favorite: false,
    stars: 1.0,
    imageUrl: 'assets/C03 - Athena_Catering.jpg',
    origins: ['Gorordo branch Athena'],
    cateringPacks: ['25 Packs', '50 Packs', '100 Packs'],
    },
    {
    id: 'C04',
    name: 'RedCarpet Catering',
    location: 'Talamban Branch',
    tags: ['RedCarpet','Talamban'],
    favorite: false,
    stars: 5.0,
    imageUrl: 'assets/C04 - RedCarpet_Catering.jpg',
    origins: ['Talamban branch amigos'],
    cateringPacks: ['25 Packs', '50 Packs', '100 Packs'],
    },
    {
    id: 'C05',
    name: 'Sonnet\'s Catering',
    location: 'Tisa Branch',
    tags: ['Sonnet','Naga'],
    favorite: false,
    stars: 4.0,
    imageUrl: 'assets/C05 - Sonnet_Catering.jpg',
    origins: ['Tisa branch amigos'],
    cateringPacks: ['25 Packs', '50 Packs', '100 Packs'],
    },
]